/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author FABIAN
 */
public class frm_GestionPagos extends javax.swing.JInternalFrame {

    private gestores.GestorPagos gestorPagos;
    private gestores.GestorReservas gestorReservas;
    /**
     * Creates new form frm_GestionPagos
     */
    public frm_GestionPagos(gestores.GestorPagos gestorP, gestores.GestorReservas gestorR) {
    initComponents();
    this.gestorPagos = gestorP;
    this.gestorReservas = gestorR;
    
    // Si ya tenías el método llenarCombos() o actualizarTabla(), 
    // asegúrate de llamarlos después de asignar los gestores:
    llenarCombos();
    cargarReservas();
    actualizarTabla();
}

    /** Llena el combo de reservas con las reservas realmente registradas en el sistema. */
    private void cargarReservas() {
        cmbReservas.removeAllItems();
        for (modelo.Reserva r : gestorReservas.listarTodas()) {
            cmbReservas.addItem(r);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReserva = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        lblMontoPagar = new javax.swing.JLabel();
        btnRegistrarPago = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPagos = new javax.swing.JTable();
        cmbTipoPago = new javax.swing.JComboBox<>();
        cmbMetodoPago = new javax.swing.JComboBox<>();
        txtTipoPago = new javax.swing.JLabel();
        txtMetodoPago = new javax.swing.JLabel();
        cmbReservas = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gestion de Pagos");

        lblReserva.setText("Reserva");

        lblMontoPagar.setText("Monto a Pagar");

        btnRegistrarPago.setText("Registrar Pago");
        btnRegistrarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPagoActionPerformed(evt);
            }
        });

        tblPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Reserva", "Monto a Pagar", "Tipo de Pago", "Metodo de Pago"
            }
        ));
        jScrollPane1.setViewportView(tblPagos);

        txtTipoPago.setText("Tipo de Pago");

        txtMetodoPago.setText("Metodo de Pago");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegistrarPago)
                .addGap(325, 325, 325))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(cmbReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(cmbTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(lblReserva)
                                .addGap(93, 93, 93)
                                .addComponent(lblMontoPagar)
                                .addGap(84, 84, 84)
                                .addComponent(txtTipoPago)))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMetodoPago)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReserva)
                    .addComponent(lblMontoPagar)
                    .addComponent(txtTipoPago)
                    .addComponent(txtMetodoPago))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnRegistrarPago)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPagoActionPerformed
        // TODO add your handling code here:
        
        try {
        // 1. Validaciones
        if (cmbReservas.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una reserva.");
            return;
        }

        modelo.Reserva reservaSel = (modelo.Reserva) cmbReservas.getSelectedItem();
        double montoPago = Double.parseDouble(txtMonto.getText().trim());

        if (montoPago > reservaSel.getSaldoPendiente()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: El monto excede el saldo pendiente (S/ " + reservaSel.getSaldoPendiente() + ").");
            return;
        }
        
        if (montoPago <= 0) {
             javax.swing.JOptionPane.showMessageDialog(this, "El monto debe ser mayor a cero.");
             return;
        }

        // 2. Capturar valores de los nuevos Combos
        modelo.TipoPago tipoPagoSel = (modelo.TipoPago) cmbTipoPago.getSelectedItem();
        modelo.MetodoPago metodoSel = (modelo.MetodoPago) cmbMetodoPago.getSelectedItem();

        // 3. Crear el pago con el constructor exacto de tu clase
        modelo.Pago nuevoPago = new modelo.Pago(montoPago, tipoPagoSel, metodoSel, java.time.LocalDate.now());
        
        // 4. Registrarlo en la reserva
        boolean exito = reservaSel.registrarPago(nuevoPago);

        if (exito) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Pago registrado! Estado de la reserva: " + reservaSel.getEstado());
            txtMonto.setText("");
            actualizarTabla(); // Actualiza la tabla de pagos
            // Opcional: Si quieres que el combo de reservas se actualice al confirmarse
            // cmbReservas.repaint(); 
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Límite de pagos alcanzado para esta reserva.");
        }

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: Ingrese un monto numérico válido.");
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage());
    }
        
    }//GEN-LAST:event_btnRegistrarPagoActionPerformed

    private void llenarCombos() {
        // 1. Limpiamos por si acaso
        cmbTipoPago.removeAllItems();
        cmbMetodoPago.removeAllItems();

        // 2. Llenamos el combo de Tipo de Pago
        // .values() obtiene [CONTADO, CREDITO, etc.]
        for (modelo.TipoPago tipo : modelo.TipoPago.values()) {
            cmbTipoPago.addItem(tipo);
        }

        // 3. Llenamos el combo de Metodo de Pago
        // .values() obtiene [EFECTIVO, TARJETA, TRANSFERENCIA, etc.]
        for (modelo.MetodoPago metodo : modelo.MetodoPago.values()) {
            cmbMetodoPago.addItem(metodo);
        }
    }
    
    private void actualizarTabla() {
    // 1. Obtener el modelo de la tabla
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblPagos.getModel();
    
    // 2. Limpiar tabla
    modelo.setRowCount(0);
    
    // 3. Obtener la reserva que está seleccionada actualmente en el combo
    modelo.Reserva reservaSel = (modelo.Reserva) cmbReservas.getSelectedItem();
    
    // 4. Si hay una reserva seleccionada, mostramos sus pagos
    if (reservaSel != null) {
        modelo.Pago[] listaPagos = reservaSel.getPagos();
        
        if (listaPagos != null) {
            for (modelo.Pago p : listaPagos) {
                if (p != null) {
                    modelo.addRow(new Object[]{
                        p.getFecha(),
                        p.getTipoPago(),
                        p.getMetodo(),
                        "S/ " + p.getMonto()
                    });
                }
            }
        }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarPago;
    private javax.swing.JComboBox<modelo.MetodoPago> cmbMetodoPago;
    private javax.swing.JComboBox<modelo.Reserva> cmbReservas;
    private javax.swing.JComboBox<modelo.TipoPago> cmbTipoPago;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMontoPagar;
    private javax.swing.JLabel lblReserva;
    private javax.swing.JTable tblPagos;
    private javax.swing.JLabel txtMetodoPago;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JLabel txtTipoPago;
    // End of variables declaration//GEN-END:variables
}
