/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import modelo.Cliente;

/**
 *
 * @author FABIAN
 */
public class frm_GestionClientes extends javax.swing.JInternalFrame {
    
    // Variable interna para manipular el gestor
    private gestores.GestorClientes gestorLocal;

    // Modificamos el constructor para pedir el gestor
    public frm_GestionClientes(gestores.GestorClientes gestorC) {
        initComponents();
        this.gestorLocal = gestorC; // Se guard para poder usarlo en los botones
        cargarClientesExistentes();
    }

    /** Carga en la tabla los clientes que ya estaban registrados, para que
     *  no se vean "perdidos" al cerrar y volver a abrir esta ventana. */
    private void cargarClientesExistentes() {
        javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) tblClientes.getModel();
        modeloTabla.setRowCount(0);
        java.time.format.DateTimeFormatter formato = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
        for (Cliente c : gestorLocal.listarTodos()) {
            modeloTabla.addRow(new Object[]{
                c.getNombres(), c.getApellidos(), c.getDocumento(), c.getNacionalidad(),
                c.getFechaNacimiento().format(formato), c.getTelefono(), c.getCorreo()
            });
        }
    }
    
    

    /**
     * Creates new form frm_GestionClientes
     */
    public frm_GestionClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblNacionalidad = new javax.swing.JLabel();
        lblFechaN = new javax.swing.JLabel();
        txtNacion = new javax.swing.JTextField();
        txtFechaN = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        setClosable(true);
        setIconifiable(true);
        setTitle("Gestión de Clientes");

        lblNombres.setText("Nombres");

        lblApellido.setText("Apellidos");

        lblDNI.setText("DNI o Pasaporte");

        lblCorreo.setText("Correo");

        lblNacionalidad.setText("Nacionalidad");

        lblFechaN.setText("Fecha de Nacimiento");

        lblTelefono.setText("Teléfono");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellidos", "DNI", "Nacionalidad", "Fecha de Nacimiento", "Teléfono", "Correo"
            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombres))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblApellido)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtNacion, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblNacionalidad)
                                        .addGap(70, 70, 70)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaN)
                                    .addComponent(txtFechaN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTelefono)
                                        .addGap(68, 68, 68))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(btnRegistrar)
                                .addGap(66, 66, 66)
                                .addComponent(btnModificar)
                                .addGap(82, 82, 82)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCorreo)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDNI)
                                .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnEliminar))))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNombres)
                        .addComponent(lblDNI)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNacionalidad)
                    .addComponent(lblFechaN)
                    .addComponent(lblTelefono)
                    .addComponent(lblCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        try {
            // 1. Capturar los textos ingresados en las cajas (con trim() para
            //    evitar espacios accidentales que impidan encontrar al cliente despues)
            String nombres = txtNombres.getText().trim();
            String apellidos = txtApellidos.getText().trim();
            String dni = txtDNI.getText().trim();
            String nacionalidad = txtNacion.getText().trim();
            String fechaNacString = txtFechaN.getText().trim(); // Lo capturamos como String temporalmente
            String telefono = txtTelefono.getText().trim();
            String correo = txtCorreo.getText().trim();

            // Validación rápida: Que no intenten registrar un cliente vacío
            if (dni.isEmpty() || nombres.isEmpty() || apellidos.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, complete al menos DNI, Nombres y Apellidos.");
                return; 
            }

            // --- LA SOLUCIÓN ESTÁ AQUÍ ---
            // Le decimos a Java qué formato vamos a usar (Día/Mes/Año)
            java.time.format.DateTimeFormatter formato = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
            
            // Traducimos el texto a un objeto LocalDate real
            java.time.LocalDate fechaNac = java.time.LocalDate.parse(fechaNacString, formato);

            // 2. Crear el objeto Cliente (ahora sí los tipos coinciden)
            Cliente nuevoCliente = new Cliente(dni, nombres, apellidos, fechaNac, nacionalidad, telefono, correo);

            // 3. ¡LA CONEXIÓN! Lo enviamos al gestor para que lo guarde en el arreglo
            boolean registroExitoso = gestorLocal.registrar(nuevoCliente);

            if (registroExitoso) {
                // 4. Mostrar el nuevo cliente en la JTable de la pantalla (usamos el string original para que se lea bien en la tabla)
                javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblClientes.getModel();
                modelo.addRow(new Object[]{nombres, apellidos, dni, nacionalidad, fechaNacString, telefono, correo});

                // 5. Limpiar las cajas de texto
                txtNombres.setText("");
                txtApellidos.setText("");
                txtDNI.setText("");
                txtNacion.setText("");
                txtFechaN.setText("");
                txtTelefono.setText("");
                txtCorreo.setText("");

                javax.swing.JOptionPane.showMessageDialog(this, "Cliente registrado con éxito en el sistema.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: Memoria llena. Capacidad máxima de clientes alcanzada.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        } catch (java.time.format.DateTimeParseException ex) {
            // Si el usuario escribe letras o una fecha al revés, atrapamos el error para que el programa no explote
            javax.swing.JOptionPane.showMessageDialog(this, "Error: La fecha debe tener el formato exacto DD/MM/YYYY (ejemplo: 25/10/1995).", "Error de Formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        try {
            // 1. Obtenemos el modelo de la tabla
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblClientes.getModel();
            
            // 2. Averiguamos qué fila seleccionó el usuario con el mouse
            int filaSeleccionada = tblClientes.getSelectedRow();
            
            // 3. Validamos que realmente haya seleccionado algo (-1 significa que no hay selección)
            if (filaSeleccionada >= 0) {
                // Confirmación de seguridad antes de borrar
                int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, 
                    "¿Está seguro de eliminar este cliente?", 
                    "Confirmar Eliminación", 
                    javax.swing.JOptionPane.YES_NO_OPTION);
                    
                if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
                    
                    // Capturamos el DNI de la fila
                    String dniSeleccionado = tblClientes.getValueAt(filaSeleccionada, 2).toString();
                    
                    // Borramos el cliente del arreglo interno
                    boolean eliminado = gestorLocal.eliminar(dniSeleccionado);
                    
                    if (eliminado) {
                        // Borramos la fila visualmente
                        modelo.removeRow(filaSeleccionada);
                        javax.swing.JOptionPane.showMessageDialog(this, "Cliente eliminado correctamente.");
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "No se pudo eliminar de la memoria.");
                    }
                }
            } else {
                // Si presionó el botón sin seleccionar a nadie en la tabla
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione un cliente de la tabla primero.");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al eliminar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        try {
            int fila = tblClientes.getSelectedRow();
            
            if (fila >= 0) {
                // Validación para que no dejen campos en blanco por error
                if (txtDNI.getText().trim().isEmpty() || txtNombres.getText().trim().isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "No puede dejar el DNI o los Nombres vacíos.");
                    return;
                }

                // Traducimos el texto a un objeto LocalDate real
                java.time.format.DateTimeFormatter formato = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
                java.time.LocalDate fechaNac = java.time.LocalDate.parse(txtFechaN.getText().trim(), formato);

                // Creamos el objeto cliente con la nueva información (con trim() en cada campo)
                Cliente clienteModificado = new Cliente(
                    txtDNI.getText().trim(), txtNombres.getText().trim(), txtApellidos.getText().trim(),
                    fechaNac, txtNacion.getText().trim(), txtTelefono.getText().trim(), txtCorreo.getText().trim()
                );

                // ¡LA CONEXIÓN! Reemplazamos en la memoria a través de tu Gestor
                boolean modificado = gestorLocal.modificar(clienteModificado);

                if (modificado) {
                    // Reemplazamos los datos de esa fila con lo nuevo que se haya escrito visualmente
                    tblClientes.setValueAt(txtNombres.getText().trim(), fila, 0);
                    tblClientes.setValueAt(txtApellidos.getText().trim(), fila, 1);
                    tblClientes.setValueAt(txtDNI.getText().trim(), fila, 2);
                    tblClientes.setValueAt(txtNacion.getText().trim(), fila, 3);
                    tblClientes.setValueAt(txtFechaN.getText().trim(), fila, 4);
                    tblClientes.setValueAt(txtTelefono.getText().trim(), fila, 5);
                    tblClientes.setValueAt(txtCorreo.getText().trim(), fila, 6);
                    
                    // Limpiamos las cajas
                    txtNombres.setText("");
                    txtApellidos.setText("");
                    txtDNI.setText("");
                    txtNacion.setText("");
                    txtFechaN.setText("");
                    txtTelefono.setText("");
                    txtCorreo.setText("");
                    
                    // Deseleccionamos la fila de la tabla para que no quede marcada
                    tblClientes.clearSelection();

                    javax.swing.JOptionPane.showMessageDialog(this, "Datos del cliente actualizados con éxito.");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Error: No se encontró el DNI en el sistema original.");
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, haga clic en un cliente de la tabla primero para modificarlo.");
            }
        } catch (java.time.format.DateTimeParseException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: La fecha debe tener el formato exacto DD/MM/YYYY.", "Error de Formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al modificar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked

        try {
    // Averiguamos qué fila se clickeó
    int fila = tblClientes.getSelectedRow();
    
    // Si hay una fila seleccionada, subimos los datos a las cajas de texto
    if (fila >= 0) {
        // El número al final (0, 1, 2...) es el número de la columna en tu tabla
        txtNombres.setText(tblClientes.getValueAt(fila, 0).toString());
        txtApellidos.setText(tblClientes.getValueAt(fila, 1).toString());
        txtDNI.setText(tblClientes.getValueAt(fila, 2).toString());
        txtNacion.setText(tblClientes.getValueAt(fila, 3).toString());
        txtFechaN.setText(tblClientes.getValueAt(fila, 4).toString());
        txtTelefono.setText(tblClientes.getValueAt(fila, 5).toString());
        txtCorreo.setText(tblClientes.getValueAt(fila, 6).toString());
    }
} catch (Exception e) {
    System.out.println("Error al seleccionar fila: " + e.getMessage());
}
    }//GEN-LAST:event_tblClientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblFechaN;
    private javax.swing.JLabel lblNacionalidad;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtFechaN;
    private javax.swing.JTextField txtNacion;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
