/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import gestores.GestorClientes;
import gestores.GestorPaquetes;

/**
 *
 * @author FABIAN
 */
public class frm_GestionReservas extends javax.swing.JInternalFrame {
    /**
     * Creates new form frm_GestionReservas
     */
    private gestores.GestorPaquetes gestorP;
    private gestores.GestorClientes gestorC;
    private gestores.GestorReservas gestorR;
    private modelo.AsesorDeViaje asesorActual;

    public frm_GestionReservas(gestores.GestorPaquetes gestorPaquetes, gestores.GestorClientes gestorClientes,
                                gestores.GestorReservas gestorReservas, modelo.AsesorDeViaje asesor) {
        initComponents();
        this.gestorP = gestorPaquetes;
        this.gestorC = gestorClientes;
        this.gestorR = gestorReservas;
        this.asesorActual = asesor;
        cargarPaquetesDisponibles();
    }

    /** Llena el combo con los paquetes activos que realmente existen en el sistema. */
    private void cargarPaquetesDisponibles() {
        for (modelo.PaqueteTuristico p : gestorP.listarTodos()) {
            cmbPaquetes.addItem(p);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbPaquetes = new javax.swing.JComboBox<>();
        txtAdultos = new javax.swing.JTextField();
        txtMenores = new javax.swing.JTextField();
        txtDniCliente = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnAgregarCliente = new javax.swing.JButton();
        lblPaquete = new javax.swing.JLabel();
        lblMenores = new javax.swing.JLabel();
        lblDnidelCliente = new javax.swing.JLabel();
        lblAdultos = new javax.swing.JLabel();
        lblTotalPagar = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientesReserva = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);

        cmbPaquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPaquetesActionPerformed(evt);
            }
        });

        txtAdultos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAdultosKeyReleased(evt);
            }
        });

        txtMenores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMenoresKeyReleased(evt);
            }
        });

        txtDniCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDniClienteKeyReleased(evt);
            }
        });

        btnRegistrar.setText("Registrar Reserva");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnAgregarCliente.setText("Agregar Cliente");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });

        lblPaquete.setText("Seleccione el Paquete");

        lblMenores.setText("Pasajeros Menores");

        lblDnidelCliente.setText("DNI del Cliente");

        lblAdultos.setText("Pasajeros Adultos");

        lblTotalPagar.setText("Total a Pagar (S/)");

        txtTotal.setEditable(false);

        tblClientesReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "DNI", "Nombres", "Apellidos"
            }
        ));
        jScrollPane1.setViewportView(tblClientesReserva);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lblAdultos)
                        .addGap(113, 113, 113)
                        .addComponent(lblMenores)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(270, 270, 270)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addComponent(txtAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMenores, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(lblPaquete))))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(cmbPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblDnidelCliente)
                        .addGap(96, 96, 96))))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(btnRegistrar)
                .addGap(127, 127, 127)
                .addComponent(btnAgregarCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblPaquete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMenores)
                    .addComponent(lblDnidelCliente)
                    .addComponent(lblAdultos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMenores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(lblTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarCliente)
                    .addComponent(btnRegistrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAdultosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdultosKeyReleased
        // TODO add your handling code here:   
    try {
        // 1. Obtenemos el paquete seleccionado
        modelo.PaqueteTuristico p = (modelo.PaqueteTuristico) cmbPaquetes.getSelectedItem();
        
        // 2. Obtenemos los números de pasajeros (si están vacíos, usamos 0)
        int adultos = txtAdultos.getText().isEmpty() ? 0 : Integer.parseInt(txtAdultos.getText());
        int menores = txtMenores.getText().isEmpty() ? 0 : Integer.parseInt(txtMenores.getText());
        
        // 3. Calculamos usando la lógica que ya tiene la clase Reserva 
        double precioBase = p.getPrecioPorPersona();
        double total = (adultos * precioBase) + (menores * precioBase * 0.5);
        
        // 4. Se muestrra en el campo de texto
        txtTotal.setText(String.format("%.2f", total));
        
    } catch (Exception e) {
        // Si el usuario escribe letras en vez de números, no hacemos nada o limpiamos
        txtTotal.setText("0.00");
    }    
    }//GEN-LAST:event_txtAdultosKeyReleased

    private void txtDniClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniClienteKeyReleased
        // El DNI del cliente no debe afectar el calculo del precio total.
        // (Antes este metodo recalculaba el total por error, copiado de
        // txtAdultosKeyReleased/txtMenoresKeyReleased; se removio esa logica).
    }//GEN-LAST:event_txtDniClienteKeyReleased

    private void txtMenoresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMenoresKeyReleased
        // TODO add your handling code here:
        
        try {
        // 1. Obtenemos el paquete seleccionado
        modelo.PaqueteTuristico p = (modelo.PaqueteTuristico) cmbPaquetes.getSelectedItem();
        
        // 2. Obtenemos los números de pasajeros (si están vacíos, usamos 0)
        int adultos = txtAdultos.getText().isEmpty() ? 0 : Integer.parseInt(txtAdultos.getText());
        int menores = txtMenores.getText().isEmpty() ? 0 : Integer.parseInt(txtMenores.getText());
        
        // 3. Calculamos usando la lógica que ya tiene la clase Reserva 
        double precioBase = p.getPrecioPorPersona();
        double total = (adultos * precioBase) + (menores * precioBase * 0.5);
        
        // 4. Se muestrra en el campo de texto
        txtTotal.setText(String.format("%.2f", total));
        
    } catch (Exception e) {
        // Si el usuario escribe letras en vez de números, no hacemos nada o limpiamos
        txtTotal.setText("0.00");
    } 
        
    }//GEN-LAST:event_txtMenoresKeyReleased

    private void cmbPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaquetesActionPerformed
        // TODO add your handling code here:
        
        try {
        // 1. Obtenemos el paquete seleccionado
        modelo.PaqueteTuristico p = (modelo.PaqueteTuristico) cmbPaquetes.getSelectedItem();
        
        // 2. Obtenemos los números de pasajeros (si están vacíos, usamos 0)
        int adultos = txtAdultos.getText().isEmpty() ? 0 : Integer.parseInt(txtAdultos.getText());
        int menores = txtMenores.getText().isEmpty() ? 0 : Integer.parseInt(txtMenores.getText());
        
        // 3. Calculamos usando la lógica que ya tiene la clase Reserva 
        double precioBase = p.getPrecioPorPersona();
        double total = (adultos * precioBase) + (menores * precioBase * 0.5);
        
        // 4. Se muestrra en el campo de texto
        txtTotal.setText(String.format("%.2f", total));
        
    } catch (Exception e) {
        txtTotal.setText("0.00");
    } 
        
    }//GEN-LAST:event_cmbPaquetesActionPerformed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        // TODO add your handling code here:
        
        String dniBuscado = txtDniCliente.getText().trim();
    
    if (dniBuscado.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese un DNI.");
        return;
    }

    // Buscamos al cliente usando el gestor que pasamos por el constructor
    // NOTA: Asegúrate de que el método se llame 'buscarCliente' o similar en tu GestorClientes
    modelo.Cliente clienteEncontrado = gestorC.buscarPorDocumento(dniBuscado);

    if (clienteEncontrado != null) {
        // Agregamos el cliente a la tabla visual
        javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) tblClientesReserva.getModel();
        
        // Asumiendo que tu tabla tiene columnas: DNI, Nombre, Apellido
        modeloTabla.addRow(new Object[]{
            clienteEncontrado.getDocumento(), 
            clienteEncontrado.getNombres(), 
            clienteEncontrado.getApellidos()
        });
        
        // Limpiamos la caja de texto para buscar otro
        txtDniCliente.setText("");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Cliente no encontrado. Regístrelo en el módulo de Clientes primero.");
    }
        
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        
        try {
        // 1. Validamos que haya un paquete seleccionado
        if (cmbPaquetes.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un paquete turístico.");
            return;
        }
        modelo.PaqueteTuristico paqueteSel = (modelo.PaqueteTuristico) cmbPaquetes.getSelectedItem();

        // 2. Obtenemos la cantidad de pasajeros
        int adultos = txtAdultos.getText().isEmpty() ? 0 : Integer.parseInt(txtAdultos.getText());
        int menores = txtMenores.getText().isEmpty() ? 0 : Integer.parseInt(txtMenores.getText());
        
        if (adultos == 0 && menores == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar al menos un pasajero.");
            return;
        }

        // 3. Obtenemos los clientes de la tabla y armamos el arreglo que pide el gestor
        javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) tblClientesReserva.getModel();
        int cantidadClientesTabla = modeloTabla.getRowCount();
        
        if (cantidadClientesTabla == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe agregar al menos un cliente a la tabla.");
            return;
        }

        modelo.Cliente[] grupoClientes = new modelo.Cliente[cantidadClientesTabla];
        for (int i = 0; i < cantidadClientesTabla; i++) {
            // Asumiendo que el DNI está en la columna 0 de tu tabla
            String dniFila = modeloTabla.getValueAt(i, 0).toString(); 
            // Buscamos el objeto Cliente completo usando tu GestorClientes
            grupoClientes[i] = gestorC.buscarPorDocumento(dniFila);
        }

        // 4. Asesor que gestiona la reserva (el que inicio sesion, recibido por constructor)
        // 5. LLAMAMOS AL GESTOR QUE TE PASARON (Aquí ocurre la magia)
        // Ojo: Asegúrate de que tu Jframe ya tenga la variable 'gestorR' (tu GestorReservas) instanciada.
        modelo.Reserva nuevaReserva = gestorR.crearReserva(
            paqueteSel, 
            asesorActual, 
            grupoClientes, 
            adultos, 
            menores, 
            java.time.LocalDate.now()
        );

        // 6. Verificamos si la reserva se creó con éxito o si rebotó por falta de cupo
        if (nuevaReserva != null) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "¡Reserva confirmada exitosamente!\nTotal a pagar: S/ " + nuevaReserva.getPrecioTotal());
                
            // Limpiamos la pantalla para una nueva venta
            modeloTabla.setRowCount(0);
            txtAdultos.setText("");
            txtMenores.setText("");
            txtTotal.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error: No hay cupos suficientes en el paquete o se alcanzó el límite de reservas.");
        }

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese números válidos en los campos de pasajeros.");
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage());
    }
        
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<modelo.PaqueteTuristico> cmbPaquetes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdultos;
    private javax.swing.JLabel lblDnidelCliente;
    private javax.swing.JLabel lblMenores;
    private javax.swing.JLabel lblPaquete;
    private javax.swing.JLabel lblTotalPagar;
    private javax.swing.JTable tblClientesReserva;
    private javax.swing.JTextField txtAdultos;
    private javax.swing.JTextField txtDniCliente;
    private javax.swing.JTextField txtMenores;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
