/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author FABIAN
 */
public class frm_GestionResenas extends javax.swing.JInternalFrame {

    private gestores.GestorResenas gestorResenas;
    private gestores.GestorReservas gestorReservas;
    /**
     * Creates new form frm_GestionResenas
     */
    public frm_GestionResenas(gestores.GestorResenas gResenas, gestores.GestorReservas gReservas) {
        initComponents();
        this.gestorResenas = gResenas;
        this.gestorReservas = gReservas;
        
        llenarCombos();
        actualizarTabla();
    }
    
    
    private void llenarCombos() {
        // 1. Llenamos las calificaciones del 1 al 5
        cmbCalificacion.removeAllItems();
        for (int i = 1; i <= 5; i++) {
            cmbCalificacion.addItem(i);
        }

        // 2. Llenamos el combo con las reservas que existen en el sistema
        cmbReserva.removeAllItems();
        modelo.Reserva[] reservasExistentes = gestorReservas.listarTodas();
        if (reservasExistentes != null) {
            for (modelo.Reserva r : reservasExistentes) {
                if (r != null) {
                    cmbReserva.addItem(r);
                }
            }
        }
    }
    
    private void actualizarTabla() {
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblResenas.getModel();
    modelo.setRowCount(0);
    
    modelo.Resena[] lista = gestorResenas.listarTodas();
    if (lista != null) {
        for (modelo.Resena r : lista) {
            if (r != null) {
                // Obtenemos el titular de la reserva (el primer cliente del arreglo)
                String nombreCliente = "Sin titular";
                modelo.Cliente[] clientesReserva = r.getReserva().getClientes();
                if (clientesReserva != null && clientesReserva.length > 0 && clientesReserva[0] != null) {
                    nombreCliente = clientesReserva[0].getNombres() + " " + clientesReserva[0].getApellidos();
                }

                modelo.addRow(new Object[]{
                    r.getFecha(),
                    nombreCliente,
                    r.getPaquete().getNombre(),
                    r.getCalificacion(),
                    r.getComentario(),
                    r.esPositiva() ? "Sí" : "No"
                });
            }
        }
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbReserva = new javax.swing.JComboBox<>();
        cmbCalificacion = new javax.swing.JComboBox<>();
        lblReserva = new javax.swing.JLabel();
        lblCalificacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComentario = new javax.swing.JTextArea();
        lblComentario = new javax.swing.JLabel();
        btnGuardarResena = new javax.swing.JButton();
        btnEliminarResena = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblResenas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gestion de Reseñas");

        lblReserva.setText("Reserva");

        lblCalificacion.setText("Calificacion");

        txtComentario.setColumns(20);
        txtComentario.setRows(5);
        jScrollPane1.setViewportView(txtComentario);

        lblComentario.setText("Comentario");

        btnGuardarResena.setText("Guardar Reseña");
        btnGuardarResena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarResenaActionPerformed(evt);
            }
        });

        btnEliminarResena.setText("Eliminar Reseña");
        btnEliminarResena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarResenaActionPerformed(evt);
            }
        });

        tblResenas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Reserva", "Calificacion", "Comentario"
            }
        ));
        jScrollPane2.setViewportView(tblResenas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblReserva)
                        .addGap(186, 186, 186)
                        .addComponent(lblCalificacion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardarResena)
                                .addGap(95, 95, 95)
                                .addComponent(btnEliminarResena)))))
                .addGap(180, 180, 180))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(lblComentario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReserva)
                    .addComponent(lblCalificacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(lblComentario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarResena)
                    .addComponent(btnEliminarResena))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarResenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarResenaActionPerformed
        // TODO add your handling code here:
        
        try {
        if (cmbReserva.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una reserva válida.");
            return;
        }

        String comentario = txtComentario.getText().trim();
        if (comentario.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, escriba un comentario.");
            return;
        }

        modelo.Reserva reservaSel = (modelo.Reserva) cmbReserva.getSelectedItem();
        
        // Evitamos que una misma reserva tenga múltiples reseñas
        if (reservaSel.getResena() != null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Esta reserva ya cuenta con una reseña registrada.");
            return;
        }

        int calificacion = (Integer) cmbCalificacion.getSelectedItem();

        // 1. Creamos la reseña
        modelo.Resena nuevaResena = new modelo.Resena(reservaSel, calificacion, comentario);

        // 2. La guardamos en el Gestor principal
        boolean exito = gestorResenas.registrar(nuevaResena);

        if (exito) {
            // 3. ¡La magia! Vinculamos la reseña directamente a la Reserva usando tu método
            reservaSel.registrarResena(nuevaResena);

            javax.swing.JOptionPane.showMessageDialog(this, "¡Reseña registrada con éxito!");
            txtComentario.setText("");
            actualizarTabla();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Se alcanzó el límite de reseñas en el sistema.");
        }

    } catch (IllegalArgumentException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error: " + e.getMessage());
    }
        
        
    }//GEN-LAST:event_btnGuardarResenaActionPerformed

    private void btnEliminarResenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarResenaActionPerformed
        // TODO add your handling code here:
        
        try {
        if (cmbReserva.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una reserva de la lista.");
            return;
        }

        modelo.Reserva reservaSel = (modelo.Reserva) cmbReserva.getSelectedItem();

        // Verificamos si realmente tiene una reseña para eliminar
        if (reservaSel.getResena() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Esta reserva no tiene ninguna reseña registrada.");
            return;
        }

        // Pedimos confirmación
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Está seguro que desea eliminar la reseña?", 
            "Confirmar Eliminación", 
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE);

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            
            // 1. La eliminamos del gestor principal
            boolean exito = gestorResenas.eliminarPorReserva(reservaSel);

            if (exito) {
                // 2. ¡Importante! Rompemos el vínculo en la Reserva pasándole 'null'
                reservaSel.registrarResena(null);
                
                javax.swing.JOptionPane.showMessageDialog(this, "Reseña eliminada correctamente.");
                actualizarTabla();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error. No se pudo eliminar la reseña.");
            }
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage());
    }
        
        
    }//GEN-LAST:event_btnEliminarResenaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarResena;
    private javax.swing.JButton btnGuardarResena;
    private javax.swing.JComboBox<Integer> cmbCalificacion;
    private javax.swing.JComboBox<modelo.Reserva> cmbReserva;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCalificacion;
    private javax.swing.JLabel lblComentario;
    private javax.swing.JLabel lblReserva;
    private javax.swing.JTable tblResenas;
    private javax.swing.JTextArea txtComentario;
    // End of variables declaration//GEN-END:variables
}
