/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author FABIAN
 */
public class frm_GestionDestinos extends javax.swing.JInternalFrame {

    private gestores.GestorDestinos gestorDestinos;
    /**
     * Creates new form frm_GestionDestinos
     */
    public frm_GestionDestinos(gestores.GestorDestinos gestorD) {
        initComponents();
        this.gestorDestinos = gestorD;
        cargarDestinosExistentes();
    }

    /** Carga en la tabla los destinos que ya estaban registrados, para que
     *  no se vean "perdidos" al cerrar y volver a abrir esta ventana. */
    private void cargarDestinosExistentes() {
        javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) tblDestinos.getModel();
        modeloTabla.setRowCount(0);
        for (modelo.DestinoTuristico d : gestorDestinos.listarTodos()) {
            modeloTabla.addRow(new Object[]{d.getNombre(), d.getPais(), d.getCiudad(), d.getClima()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombredelDestino = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblDuracioenDias = new javax.swing.JLabel();
        txtDias = new javax.swing.JTextField();
        lblPais = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        lblPrecioBase = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDestinos = new javax.swing.JTable();
        txtIdioma = new javax.swing.JTextField();
        lblCiudad = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        lblDesc = new javax.swing.JLabel();
        lblClima = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        txtClima = new javax.swing.JTextField();
        lblIdioma = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gestion de Destinos");

        lblNombredelDestino.setText("Nombre del Destino");

        lblDuracioenDias.setText("Duración en Días");

        lblPais.setText("Pais");

        lblPrecioBase.setText("Precio Base");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tblDestinos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre del Destino", "Pais", "Ciudad", "Clima", "Duración en Días", "Precio Base", "Descuento", "Idioma"
            }
        ));
        jScrollPane1.setViewportView(tblDestinos);

        lblCiudad.setText("Ciudad");

        lblDesc.setText("Descuento");

        lblClima.setText("Clima");

        lblIdioma.setText("Idioma");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDuracioenDias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDias)
                    .addComponent(txtNombre)
                    .addComponent(lblNombredelDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(lblPais)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(75, 75, 75)
                                                .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblIdioma))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(112, 112, 112)
                                                .addComponent(lblCiudad)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblClima)))
                                        .addGap(140, 140, 140)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnModificar)
                                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblPrecioBase)
                        .addGap(125, 125, 125)
                        .addComponent(lblDesc)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 189, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(646, Short.MAX_VALUE)
                    .addComponent(txtClima, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(204, 204, 204)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPais)
                        .addComponent(lblNombredelDestino)
                        .addComponent(lblCiudad)
                        .addComponent(lblClima)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnModificar)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecioBase)
                            .addComponent(lblDesc)
                            .addComponent(lblIdioma))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar)
                            .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblDuracioenDias)
                        .addGap(7, 7, 7)
                        .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(txtClima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(556, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
        // 1. Capturamos los datos de las cajas de texto (con trim() para
        //    evitar espacios accidentales que afecten futuras busquedas)
        String nombre = txtNombre.getText().trim();
        String pais = txtPais.getText().trim();
        String ciudad = txtCiudad.getText().trim();
        String desc = txtDesc.getText().trim();
        String clima = txtClima.getText().trim();
        String idioma = txtIdioma.getText().trim();
        String imagen = "ruta_default.jpg"; // Por ahora dejamos una ruta fija

        // Validación simple para no registrar campos vacíos
        if (nombre.isEmpty() || pais.isEmpty() || ciudad.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El Nombre, País y Ciudad son obligatorios.");
            return;
        }

        // 2. Creamos el objeto DestinoTuristico con los datos capturados
        modelo.DestinoTuristico nuevoDestino = new modelo.DestinoTuristico(
            nombre, pais, ciudad, desc, clima, idioma, imagen
        );
        
        // 3. Registramos en el gestor
        if (gestorDestinos.registrar(nuevoDestino)) {
            // 4. Actualizamos la tabla visual
            javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) tblDestinos.getModel();
            modeloTabla.addRow(new Object[]{nombre, pais, ciudad, clima});
            
            // Limpiamos los campos después de registrar
            txtNombre.setText("");
            txtPais.setText("");
            txtCiudad.setText("");
            txtDesc.setText("");
            txtClima.setText("");
            txtIdioma.setText("");
            
            javax.swing.JOptionPane.showMessageDialog(this, "Destino registrado correctamente.");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Capacidad máxima alcanzada.");
        }
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        
        
        int filaSeleccionada = tblDestinos.getSelectedRow();
    
    if (filaSeleccionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione una fila de la tabla primero.");
        return;
    }

    // Obtenemos los datos originales de la tabla para buscar en el gestor
    javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) tblDestinos.getModel();
    String nombreOriginal = (String) modeloTabla.getValueAt(filaSeleccionada, 0);
    String ciudadOriginal = (String) modeloTabla.getValueAt(filaSeleccionada, 1);

    // Creamos el nuevo objeto con los datos modificados de las cajas
    modelo.DestinoTuristico destinoModificado = new modelo.DestinoTuristico(
        txtNombre.getText(), txtPais.getText(), txtCiudad.getText(), 
        txtDesc.getText(), txtClima.getText(), txtIdioma.getText(), "ruta.jpg"
    );

    // Llamamos al método modificar que creamos en tu GestorDestinos
    if (gestorDestinos.modificar(nombreOriginal, ciudadOriginal, destinoModificado)) {
        // Actualizamos la tabla visual
        modeloTabla.setValueAt(txtNombre.getText(), filaSeleccionada, 0);
        modeloTabla.setValueAt(txtPais.getText(), filaSeleccionada, 1);
        modeloTabla.setValueAt(txtCiudad.getText(), filaSeleccionada, 2);
        modeloTabla.setValueAt(txtClima.getText(), filaSeleccionada, 3);
        
        javax.swing.JOptionPane.showMessageDialog(this, "Destino modificado correctamente.");
    }
        
        
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         
        int filaSeleccionada = tblDestinos.getSelectedRow();
        
        if (filaSeleccionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione la fila que desea eliminar.");
        return;
    }
        javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) tblDestinos.getModel();
        String nombre = (String) modeloTabla.getValueAt(filaSeleccionada, 0);
        String ciudad = (String) modeloTabla.getValueAt(filaSeleccionada, 1);
        
        if (gestorDestinos.eliminar(nombre, ciudad)) {
        modeloTabla.removeRow(filaSeleccionada);
        javax.swing.JOptionPane.showMessageDialog(this, "Destino eliminado.");
        
        } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar.");
        
        }    
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblClima;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblDuracioenDias;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblNombredelDestino;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblPrecioBase;
    private javax.swing.JTable tblDestinos;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtClima;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextField txtIdioma;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
