/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author FABIAN
 */
public class frm_Principal extends javax.swing.JFrame {
    private modelo.Empleado usuarioLogueado; // Variable para guardar el empleado

    // Todos los gestores llegan desde frmLogin (creados una sola vez por
    // ejecucion del programa) para que cerrar sesion no borre los datos.
    private gestores.GestorEmpleados gestorEmpleados;
    private gestores.GestorClientes gestorClientes;
    private gestores.GestorDestinos gestorDestinos;
    private gestores.GestorPaquetes gestorPaquetes;
    private gestores.GestorReservas gestorReservas;
    private gestores.GestorResenas gestorResenas;
    private gestores.GestorPagos gestorPagos;
    private gestores.GestorPromociones gestorPromociones;

    // Menus agregados por codigo (ver agregarMenusFaltantes())
    private javax.swing.JMenuItem jMenuItemEmpleados;
    private javax.swing.JMenuItem jMenuItemPromociones;
    private javax.swing.JMenuItem jMenuItemCupos;
    private javax.swing.JMenuItem jMenuItemCerrarSesion;

    /**
     * Creates new form frm_Principal
     * @param emp empleado que inicio sesion
     * @param gestorEmpleados los mismos gestores usados en el login, para
     *        que las pantallas de gestion operen sobre los mismos datos
     *        y estos sobrevivan a un cierre de sesion
     */
    public frm_Principal(modelo.Empleado emp,
                          gestores.GestorEmpleados gestorEmpleados,
                          gestores.GestorClientes gestorClientes,
                          gestores.GestorDestinos gestorDestinos,
                          gestores.GestorPaquetes gestorPaquetes,
                          gestores.GestorReservas gestorReservas,
                          gestores.GestorResenas gestorResenas,
                          gestores.GestorPagos gestorPagos,
                          gestores.GestorPromociones gestorPromociones) {
        initComponents();
        this.usuarioLogueado = emp;
        this.gestorEmpleados = gestorEmpleados;
        this.gestorClientes = gestorClientes;
        this.gestorDestinos = gestorDestinos;
        this.gestorPaquetes = gestorPaquetes;
        this.gestorReservas = gestorReservas;
        this.gestorResenas = gestorResenas;
        this.gestorPagos = gestorPagos;
        this.gestorPromociones = gestorPromociones;
        agregarMenusFaltantes();
        aplicarPermisos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        lblUsuarioMostrado = new javax.swing.JLabel();
        lblRolMostrado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        txtMantenimiento = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        txtOperaciones = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        txtReservas = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setText("CAMINOS VERDES");

        lblRol.setText("Rol:");
        lblRol.setToolTipText("");

        lblUsuario.setText("Usuario: ");
        lblUsuario.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                lblUsuarioAncestorRemoved(evt);
            }
        });

        jDesktopPane2.setForeground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );

        txtMantenimiento.setText("Paquetes");

        jMenuItem3.setText("Gestionar Paquetes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        txtMantenimiento.add(jMenuItem3);

        jMenuBar1.add(txtMantenimiento);

        txtOperaciones.setText("Operaciones");

        jMenuItem5.setText("Gestionar Pagos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        txtOperaciones.add(jMenuItem5);

        jMenuItem6.setText("Gestionar Reseñas");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        txtOperaciones.add(jMenuItem6);

        jMenuItem7.setText("Reportes");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        txtOperaciones.add(jMenuItem7);

        jMenuBar1.add(txtOperaciones);

        jMenu1.setText("Destinos Turísticos");

        jMenuItem1.setText("Gestionar Destinos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        txtReservas.setText("Reservas");

        jMenuItem2.setText("GestionarReservas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        txtReservas.add(jMenuItem2);

        jMenuBar1.add(txtReservas);

        jMenu2.setText("Clientes");

        jMenuItem4.setText("Gestionar Clientes");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDesktopPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 233, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUsuarioMostrado, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)))
                        .addGap(10, 10, 10)
                        .addComponent(lblRol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRolMostrado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRol)
                    .addComponent(lblUsuario)
                    .addComponent(lblRolMostrado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioMostrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDesktopPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        // 1. Instanciamos la ventana pasándole el gestor central
        frm_GestionDestinos ventanaDestinos = new frm_GestionDestinos(gestorDestinos);        
        // 2. La agregamos al fondo gris (tu JDesktopPane1)
        jDesktopPane2.add(ventanaDestinos);

        // 3. La mostramos en pantalla
        ventanaDestinos.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // Solo un Asesor de Viaje puede crear reservas (regla de negocio del enunciado)
        if (!(usuarioLogueado instanceof modelo.AsesorDeViaje)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Solo un Asesor de Viaje puede gestionar reservas.");
            return;
        }
        modelo.AsesorDeViaje asesor = (modelo.AsesorDeViaje) usuarioLogueado;
        frm_GestionReservas f = new frm_GestionReservas(gestorPaquetes, gestorClientes, gestorReservas, asesor);
        jDesktopPane2.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        frm_GestionPaquetes ventanaPaquetes = new frm_GestionPaquetes(gestorPaquetes);
        jDesktopPane2.add(ventanaPaquetes);
        ventanaPaquetes.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        frm_GestionPagos f = new frm_GestionPagos(gestorPagos, gestorReservas);
        jDesktopPane2.add(f); // jDesktopPane1 es tu contenedor principal
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        frm_GestionResenas f = new frm_GestionResenas(gestorResenas, gestorReservas);
        jDesktopPane2.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        frm_Reportes f = new frm_Reportes(gestorReservas, gestorPaquetes, gestorClientes);
        jDesktopPane2.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        frm_GestionClientes f = new frm_GestionClientes(gestorClientes);
        jDesktopPane2.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void lblUsuarioAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblUsuarioAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsuarioAncestorRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Vista previa de esta pantalla sola, con datos de prueba
                gestores.GestorEmpleados gestorPrueba = new gestores.GestorEmpleados();
                modelo.Administrador admin = new modelo.Administrador("00000000", "Prueba", "Prueba", "admin", "admin");
                gestorPrueba.registrar(admin);
                new frm_Principal(admin, gestorPrueba,
                        new gestores.GestorClientes(), new gestores.GestorDestinos(),
                        new gestores.GestorPaquetes(), new gestores.GestorReservas(),
                        new gestores.GestorResenas(), new gestores.GestorPagos(),
                        new gestores.GestorPromociones()).setVisible(true);
            }
        });
    }
    
    /**
     * Agrega al JMenuBar las opciones que no existian en el diseño original:
     * Gestionar Empleados y Gestionar Promociones (para el Administrador),
     * y Ver Cupos e Itinerarios (para el Operador). Se agregan por codigo
     * en vez de con el editor visual para no romper el .form existente.
     */
    private void agregarMenusFaltantes() {
        javax.swing.JMenu menuAdmin = new javax.swing.JMenu("Administracion");

        jMenuItemEmpleados = new javax.swing.JMenuItem("Gestionar Empleados");
        jMenuItemEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frm_GestionEmpleados f = new frm_GestionEmpleados(gestorEmpleados);
                jDesktopPane2.add(f);
                f.setVisible(true);
            }
        });
        menuAdmin.add(jMenuItemEmpleados);

        jMenuItemPromociones = new javax.swing.JMenuItem("Gestionar Promociones");
        jMenuItemPromociones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frm_GestionPromociones f = new frm_GestionPromociones(gestorPromociones);
                jDesktopPane2.add(f);
                f.setVisible(true);
            }
        });
        menuAdmin.add(jMenuItemPromociones);
        jMenuBar1.add(menuAdmin);

        javax.swing.JMenu menuConsultas = new javax.swing.JMenu("Consultas");
        jMenuItemCupos = new javax.swing.JMenuItem("Ver Cupos e Itinerarios");
        jMenuItemCupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frm_VerCupos f = new frm_VerCupos(gestorPaquetes);
                jDesktopPane2.add(f);
                f.setVisible(true);
            }
        });
        menuConsultas.add(jMenuItemCupos);
        jMenuBar1.add(menuConsultas);

        javax.swing.JMenu menuSesion = new javax.swing.JMenu("Sesion");
        jMenuItemCerrarSesion = new javax.swing.JMenuItem("Cerrar Sesion");
        jMenuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // Reabre el login reutilizando los MISMOS gestores (con todos
                // los datos ya registrados), para no perder informacion.
                frmLogin login = new frmLogin(gestorEmpleados, gestorClientes, gestorDestinos,
                        gestorPaquetes, gestorReservas, gestorResenas, gestorPagos, gestorPromociones);
                login.setVisible(true);
                dispose();
            }
        });
        menuSesion.add(jMenuItemCerrarSesion);
        jMenuBar1.add(menuSesion);
    }

    /**
     * Restringe las opciones del menu segun el rol del empleado logueado,
     * conforme al requerimiento 12 del enunciado:
     * Administrador -> empleados, destinos, paquetes, promociones, reportes
     * Asesor de Viaje -> clientes, reservas, pagos, resenas, reportes
     * Operador -> solo consulta de cupos e itinerarios
     */
    private void aplicarPermisos() {
        // Por defecto, todo deshabilitado; se habilita segun el rol
        jMenuItem1.setEnabled(false); // Gestionar Destinos
        jMenuItem2.setEnabled(false); // Gestionar Reservas
        jMenuItem3.setEnabled(false); // Gestionar Paquetes
        jMenuItem4.setEnabled(false); // Gestionar Clientes
        jMenuItem5.setEnabled(false); // Gestionar Pagos
        jMenuItem6.setEnabled(false); // Gestionar Resenas
        jMenuItem7.setEnabled(false); // Reportes
        jMenuItemEmpleados.setEnabled(false);
        jMenuItemPromociones.setEnabled(false);
        jMenuItemCupos.setEnabled(false);

        if (usuarioLogueado instanceof modelo.Administrador) {
            jMenuItemEmpleados.setEnabled(true);
            jMenuItem1.setEnabled(true);
            jMenuItem3.setEnabled(true);
            jMenuItemPromociones.setEnabled(true);
            jMenuItem7.setEnabled(true);
        } else if (usuarioLogueado instanceof modelo.AsesorDeViaje) {
            jMenuItem4.setEnabled(true);
            jMenuItem2.setEnabled(true);
            jMenuItem5.setEnabled(true);
            jMenuItem6.setEnabled(true);
            jMenuItem7.setEnabled(true);
        } else if (usuarioLogueado instanceof modelo.Operador) {
            jMenuItemCupos.setEnabled(true);
        }

        lblUsuarioMostrado.setText(usuarioLogueado.getUsuario());
        lblRolMostrado.setText(usuarioLogueado.getRol());
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblRolMostrado;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioMostrado;
    private javax.swing.JMenu txtMantenimiento;
    private javax.swing.JMenu txtOperaciones;
    private javax.swing.JMenu txtReservas;
    // End of variables declaration//GEN-END:variables
}
