/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import java.time.LocalDate;
import modelo.DescuentoMontoFijo;
import modelo.DescuentoPorcentaje;

/**
 *
 * @author FABIAN
 */
public class frm_GestionPaquetes extends javax.swing.JInternalFrame {
    private modelo.PaqueteTuristico paqueteActual;
    
    public frm_GestionPaquetes() {
        initComponents(); // Esta línea crea la interfaz (el JComboBox, botones, etc.)
        
        // --- AQUÍ PONES EL CÓDIGO DEL PASO A ---
        cargarPromocionesEnCombo(); 
    }
    
    private void cargarPromocionesEnCombo() {
        cmbPromociones.removeAllItems(); // Limpiar por si acaso
        
        // Agregar las promociones (puedes crear nuevas instancias aquí)
        cmbPromociones.addItem(new DescuentoPorcentaje("PROM-001", LocalDate.now(), LocalDate.now().plusMonths(1), 0.15));
        cmbPromociones.addItem(new DescuentoMontoFijo("PROM-002", LocalDate.now(), LocalDate.now().plusMonths(1), 50.0));
    }

    /**
     * Creates new form frm_GestionPaquetes
     */
    
    private gestores.GestorPaquetes gestorP;
    
    public frm_GestionPaquetes(gestores.GestorPaquetes gestorPaquetes) {
        initComponents();
        this.gestorP = gestorPaquetes;
        llenarCombos();
        actualizarTabla();
    }
    
    private void llenarCombos() {
        cmbTipoPaquete.removeAllItems();
        for (modelo.TipoPaquete tipo : modelo.TipoPaquete.values()) {
            cmbTipoPaquete.addItem(tipo);
        }
        
        cmbEstado.removeAllItems();
        for (modelo.EstadoPaquete estado : modelo.EstadoPaquete.values()) {
            cmbEstado.addItem(estado);
        }
    }
    
    private void actualizarTabla() {
    // 1. Obtenemos el modelo de tu tabla
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblPaquetes.getModel();
    
    // 2. Limpiamos la tabla para no duplicar datos visualmente
    modelo.setRowCount(0);
    
    // 3. Le pedimos a tu gestor TODOS los paquetes registrados
    modelo.PaqueteTuristico[] lista = gestorP.listarTodos();
    
    // 4. Recorremos el arreglo y agregamos fila por fila
    if (lista != null) {
        for (modelo.PaqueteTuristico p : lista) {
            if (p != null) { // Verificación de seguridad
                modelo.addRow(new Object[]{
                    p.getCodigo(),
                    p.getNombre(),
                    p.getTipo(),
                    p.getDuracionDias(),
                    p.getDuracionNoches(),
                    p.getPrecioPorPersona(),
                    p.getCupoDisponible() + "/" + p.getCupoMaximo(),
                    p.getEstado()
                });
            }
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigoPaquete = new javax.swing.JLabel();
        lblNombrePaquete = new javax.swing.JLabel();
        lblCupos = new javax.swing.JLabel();
        lblPrecioBase = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCupos = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        cmbTipoPaquete = new javax.swing.JComboBox<>();
        cmbEstado = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPaquetes = new javax.swing.JTable();
        lblFechaSalida = new javax.swing.JLabel();
        lblFechaRetorno = new javax.swing.JLabel();
        lblDuraciónD = new javax.swing.JLabel();
        lblDuracionN = new javax.swing.JLabel();
        txtFechaSalida = new javax.swing.JTextField();
        txtFechaRetorno = new javax.swing.JTextField();
        txtDias = new javax.swing.JTextField();
        txtNoches = new javax.swing.JTextField();
        lblTipoPaquete = new javax.swing.JLabel();
        lblEstadp = new javax.swing.JLabel();
        cmbPromociones = new javax.swing.JComboBox<>();
        lblPromocion = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gestion de Paquetes");

        lblCodigoPaquete.setText("Codigo del Paquete");

        lblNombrePaquete.setText("Nombre del Paquete");

        lblCupos.setText("Cupos Disponibles");

        lblPrecioBase.setText("Precio Base");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tblPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo del Paquete", "Nombre del Paquete", "Cupos Disponibles", "Precio Base", "Fecha de Salida", "Fecha de Retorno", "Duración (Dias)", "Duracion (Noches)"
            }
        ));
        jScrollPane1.setViewportView(tblPaquetes);

        lblFechaSalida.setText("Fecha de Salida");

        lblFechaRetorno.setText("Fecha de Retorno");

        lblDuraciónD.setText("Duración (Dias)");

        lblDuracionN.setText("Duración (Noches)");

        lblTipoPaquete.setText("Tipo de Paquete");

        lblEstadp.setText("Estado");

        cmbPromociones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPromocionesActionPerformed(evt);
            }
        });

        lblPromocion.setText("Promocion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTipoPaquete)
                            .addComponent(cmbTipoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPromociones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPromocion))
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(lblFechaSalida))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCodigoPaquete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCodigo)
                                    .addComponent(txtFechaSalida))
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaRetorno)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFechaRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNombrePaquete)
                                        .addComponent(btnRegistrar)))))
                        .addGap(46, 82, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblCupos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDuraciónD)
                        .addGap(61, 61, 61))
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDias, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                .addComponent(txtCupos)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDuracionN)
                            .addComponent(txtNoches, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lblPrecioBase)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEstadp)
                .addGap(264, 264, 264))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoPaquete)
                    .addComponent(lblNombrePaquete)
                    .addComponent(lblCupos)
                    .addComponent(lblPrecioBase))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaSalida)
                    .addComponent(lblFechaRetorno)
                    .addComponent(lblDuraciónD)
                    .addComponent(lblDuracionN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoPaquete)
                    .addComponent(lblEstadp)
                    .addComponent(lblPromocion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPromociones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here: 
        try {
        // 1. Textos básicos
        String codigo = txtCodigo.getText().trim();
        String nombre = txtNombre.getText().trim();

        // 2. Números (Días, noches, precio y cupos)
        int dias = Integer.parseInt(txtDias.getText().trim());
        int noches = Integer.parseInt(txtNoches.getText().trim());
        double precio = Double.parseDouble(txtPrecio.getText().trim());
        int cuposMax = Integer.parseInt(txtCupos.getText().trim());

        // 3. Fechas
        java.time.LocalDate fechaSalida = java.time.LocalDate.parse(txtFechaSalida.getText().trim());
        java.time.LocalDate fechaRetorno = java.time.LocalDate.parse(txtFechaRetorno.getText().trim());

        // 4. Tipo de Paquete 
        modelo.TipoPaquete tipoSel = (modelo.TipoPaquete) cmbTipoPaquete.getSelectedItem();

        // 5. 
        modelo.PaqueteTuristico nuevoPaquete = new modelo.PaqueteTuristico(
            codigo, 
            nombre, 
            tipoSel, 
            dias, 
            noches, 
            precio, 
            fechaSalida, 
            fechaRetorno, 
            cuposMax
        );

        // 6. Guarda en el Gestor
        boolean exito = gestorP.registrar(nuevoPaquete);

        if (exito) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Paquete registrado exitosamente!");
            actualizarTabla();
            // Limpiamos las cajas
            txtCodigo.setText("");
            txtNombre.setText("");
            txtDias.setText("");
            txtNoches.setText("");
            txtPrecio.setText("");
            txtCupos.setText("");
            txtFechaSalida.setText("");
            txtFechaRetorno.setText("");
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Se alcanzó el límite máximo de paquetes.");
        }

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "ERROR: Verifique que Días, Noches, Precio y Cupos sean números válidos.");
    } catch (java.time.format.DateTimeParseException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: La fecha debe tener el siguiente formato (ejemplo: 2026-10-15).");
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "ERROR: " + e.getMessage());   
    }//GEN-LAST:event_btnRegistrarActionPerformed
    }
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
        // 1. Obtener el código de la caja de texto
    String codigo = txtCodigo.getText().trim();

    if (codigo.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese el Código del paquete que desea eliminar.");
        return;
    }

    // 2. Pedir confirmación de seguridad (¡Muy importante en Ingeniería de Software!)
    int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
        "¿Está seguro que desea eliminar el paquete con código: " + codigo + "?", 
        "Confirmar Eliminación", 
        javax.swing.JOptionPane.YES_NO_OPTION,
        javax.swing.JOptionPane.WARNING_MESSAGE);

    // 3. Si el usuario hace clic en "Sí" (YES_OPTION)
    if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
        
        // Llamamos a tu GestorPaquetes
        boolean exito = gestorP.eliminar(codigo);

        if (exito) {
            javax.swing.JOptionPane.showMessageDialog(this, "Paquete eliminado correctamente.");
            actualizarTabla();
            // Limpiamos la caja de texto
            txtCodigo.setText("");
            txtCodigo.requestFocus();
            
            // Aquí luego llamaremos a actualizarTabla() para que desaparezca visualmente
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: No se encontró ningún paquete con ese código.");
        }
    }
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cmbPromocionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPromocionesActionPerformed

        if (paqueteActual != null && cmbPromociones.getSelectedItem() != null) {
        modelo.Promocion promoSeleccionada = (modelo.Promocion) cmbPromociones.getSelectedItem();
        paqueteActual.setPromocion(promoSeleccionada);
        actualizarTabla();
    } 
    }//GEN-LAST:event_cmbPromocionesActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<modelo.EstadoPaquete> cmbEstado;
    private javax.swing.JComboBox<modelo.Promocion> cmbPromociones;
    private javax.swing.JComboBox<modelo.TipoPaquete> cmbTipoPaquete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigoPaquete;
    private javax.swing.JLabel lblCupos;
    private javax.swing.JLabel lblDuracionN;
    private javax.swing.JLabel lblDuraciónD;
    private javax.swing.JLabel lblEstadp;
    private javax.swing.JLabel lblFechaRetorno;
    private javax.swing.JLabel lblFechaSalida;
    private javax.swing.JLabel lblNombrePaquete;
    private javax.swing.JLabel lblPrecioBase;
    private javax.swing.JLabel lblPromocion;
    private javax.swing.JLabel lblTipoPaquete;
    private javax.swing.JTable tblPaquetes;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCupos;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextField txtFechaRetorno;
    private javax.swing.JTextField txtFechaSalida;
    private javax.swing.JTextField txtNoches;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
