/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import modelo.Empleado;

/**
 *
 * @author FABIAN
 */
public class frmLogin extends javax.swing.JFrame {

    // Todos los gestores del sistema viven aqui, se crean UNA sola vez por
    // ejecucion del programa, y se pasan de pantalla en pantalla para que
    // los datos no se pierdan al cerrar sesion y volver a entrar.
    private gestores.GestorEmpleados gestorEmpleados;
    private gestores.GestorClientes gestorClientes;
    private gestores.GestorDestinos gestorDestinos;
    private gestores.GestorPaquetes gestorPaquetes;
    private gestores.GestorReservas gestorReservas;
    private gestores.GestorResenas gestorResenas;
    private gestores.GestorPagos gestorPagos;
    private gestores.GestorPromociones gestorPromociones;

    /**
     * Primer arranque de la aplicacion: crea todos los gestores desde cero
     * y precarga los 3 empleados de prueba.
     */
    public frmLogin() {
        initComponents();
        this.gestorEmpleados = new gestores.GestorEmpleados();
        this.gestorClientes = new gestores.GestorClientes();
        this.gestorDestinos = new gestores.GestorDestinos();
        this.gestorPaquetes = new gestores.GestorPaquetes();
        this.gestorReservas = new gestores.GestorReservas();
        this.gestorResenas = new gestores.GestorResenas();
        this.gestorPagos = new gestores.GestorPagos();
        this.gestorPromociones = new gestores.GestorPromociones();
        cargarEmpleadosIniciales();
    }

    /**
     * Se usa al "Cerrar Sesion" desde frm_Principal: reutiliza los MISMOS
     * gestores (con todos los datos ya registrados) en vez de crear unos
     * nuevos vacios, para que cambiar de usuario no borre la informacion.
     */
    public frmLogin(gestores.GestorEmpleados gestorEmpleados, gestores.GestorClientes gestorClientes,
                     gestores.GestorDestinos gestorDestinos, gestores.GestorPaquetes gestorPaquetes,
                     gestores.GestorReservas gestorReservas, gestores.GestorResenas gestorResenas,
                     gestores.GestorPagos gestorPagos, gestores.GestorPromociones gestorPromociones) {
        initComponents();
        this.gestorEmpleados = gestorEmpleados;
        this.gestorClientes = gestorClientes;
        this.gestorDestinos = gestorDestinos;
        this.gestorPaquetes = gestorPaquetes;
        this.gestorReservas = gestorReservas;
        this.gestorResenas = gestorResenas;
        this.gestorPagos = gestorPagos;
        this.gestorPromociones = gestorPromociones;
        // OJO: no se llama a cargarEmpleadosIniciales() aqui, para no duplicar
        // los empleados que ya existian antes de cerrar sesion.
    }

    /**
     * Precarga un empleado por cada rol para poder iniciar sesion la primera vez.
     * Usuarios de prueba:
     *   admin / admin123       (Administrador)
     *   asesor / asesor123     (Asesor de Viaje)
     *   operador / operador123 (Operador)
     */
    private void cargarEmpleadosIniciales() {
        gestorEmpleados.registrar(new modelo.Administrador("10000001", "Ana", "Torres", "admin", "admin123"));
        gestorEmpleados.registrar(new modelo.AsesorDeViaje("10000002", "Luis", "Ramos", "asesor", "asesor123"));
        gestorEmpleados.registrar(new modelo.Operador("10000003", "Mia", "Diaz", "operador", "operador123"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        lblConstrasenia = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtContrasenia = new javax.swing.JPasswordField();
        lblBienvenida = new javax.swing.JLabel();
        lblIngreseUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsuario.setText("Usuario");

        lblConstrasenia.setText("Contraseña");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");

        lblBienvenida.setText("¡BIENVENIDO A CAMINOS VERDES!");

        lblIngreseUsuario.setText("INGRESE SU USUARIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(lblConstrasenia))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIngresar)
                                .addGap(69, 69, 69)
                                .addComponent(btnSalir))
                            .addComponent(lblBienvenida))))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIngreseUsuario)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(lblUsuario)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIngreseUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblConstrasenia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnSalir))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
       // Dentro del evento actionPerformed de tu botón "Ingresar"
       String user = txtUsuario.getText();
       String pass = new String(txtContrasenia.getPassword());
       Empleado empleado = gestorEmpleados.validarLogin(user, pass);
       if (empleado != null) {
           frm_Principal principal = new frm_Principal(empleado, gestorEmpleados, gestorClientes,
                   gestorDestinos, gestorPaquetes, gestorReservas, gestorResenas, gestorPagos, gestorPromociones);
           principal.setVisible(true);
           this.dispose(); // Cerramos el login
       } else {
           javax.swing.JOptionPane.showMessageDialog(this, "Datos Incorrectos");
       }
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblConstrasenia;
    private javax.swing.JLabel lblIngreseUsuario;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
